route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]
  routes:
    - receiver: 'teams'
      repeat_interval: 12h
      matchers:
        - severity="medium"


receivers:
  - name: 'teams'
    webhook_configs:
      - url: ""
        send_resolved: true
   
